HEADER:
  label: "About me"

PRESENTATION:
  description: |
    I am a Data Engineer with over 5 years of experience in building scalable, high-performance data pipelines for both batch and real-time processing. My expertise includes cloud platforms (AWS, GCP, Azure), data warehousing (Snowflake, BigQuery), and streamlining ETL workflows using tools like Apache Spark, Kafka, and Airflow. I am skilled in modern data architecture, implementing robust data models, and ensuring data quality through automated testing and monitoring. My experience spans multiple industries, delivering actionable insights and improving business operations through advanced data engineering practices.

DOING:
  enabled: true
  label: "What I'm doing"
  items:
    - title: "Mobile Apps"
      icon: "config/assets/icons/mobile.svg"
      description: "Professional development of applications for iOS and Android."
    - title: "Scripting"
      icon: "config/assets/icons/code.svg"
      description: "Automation and task scripting using Python to enhance efficiency and productivity."
    - title: "UI/UX Designing"
      icon: "config/assets/icons/compass.svg"
      description: "Intuitive and visually appealing user interfaces and user experiences."
    - title: "Web Development"
      icon: "config/assets/icons/laptop-code.svg"
      description: "High-quality development of sites at the professional level."

SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Fast Learner"
      icon: "config/assets/icons/bolt.svg"
      description: "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."
    - title: "Problem Solving"
      icon: "config/assets/icons/gear.svg"
      description: "I am creative and efficient in identifying and solving technical problems."
    - title: "Teamwork"
      icon: "config/assets/icons/user.svg"
      description: "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."

    - title: "Effective Communication"
      icon: "config/assets/icons/comment.svg"
      description: "I have the skill to convey ideas clearly and concisely, both technically and non-technically."

TECHNOLOGIES:
  enabled: true
  label: "Tech Experience"
  items:
    - title: "Python"
      icon: "config/assets/icons/python.svg"
    - title: "MySQL"
      icon: "config/assets/icons/mysql.svg"
    - title: "Spark"
      icon: "config/assets/icons/spark.svg"
    - title: "Azure"
      icon: "config/assets/icons/azure.svg"
    - title: "AWS"
      icon: "config/assets/icons/aws.svg"
    - title: "GCP"
      icon: "config/assets/icons/gcp.svg"
    - title: "dbt"
      icon: "config/assets/icons/dbt.svg"
    - title: "Airflow"
      icon: "config/assets/icons/airflow.svg"
    - title: "Databricks"
      icon: "config/assets/icons/databricks.svg"
    - title: "Snowflake"
      icon: "config/assets/icons/snowflake.svg"
    - title: "AI/ML"
      icon: "config/assets/icons/ai.svg"
    - title: "Docker"
      icon: "config/assets/icons/docker.svg"

