# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Data Engineer"
  name: "Umesh R"
  username: "Umesh1610" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "richard@example.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "+1 (945) 249-1233"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "Oct 16"
    icon: "calendar-outline"
  - label: "Location"
    value: "Dallas, Texas, USA"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/"
  - icon: "logo-github"
    url: "https://github.com/ivansaul"

