HEADER:
  label: "Portfolio"

PROJECTS:
  - title: "Real Time Reddit Sentiment Analysis"
    category: "Data Engineering"
    image: "config/assets/projects/senti.jpg"
    url: "https://github.com/Umesh1610/Realtime-Reddit-Sentiment-Analysis-AWS"

  - title: "Real Time Crypto Price Tracking "
    category: "Data Engineering"
    image: "config/assets/projects/crypto.png"
    url: "https://github.com/Umesh1610/Crypto-real-time-Price-Tracking-GCP"

  - title: "Real Time Flight & Weather Tracking"
    category: "Data Engineering"
    image: "config/assets/projects/flight.jpg"
    url: "https://github.com/Umesh1610/realtime_flight_track_databricks"

  - title: "F1 Racing Using Databricks"
    category: "Data Engineering"
    image: "config/assets/projects/f1.jpg"
    url: "https://github.com/Umesh1610/F1racing_dataengineering_databricks"

 
  - title: "Airbnb Snowflake DBT"
    category: "DBT"
    image: "config/assets/projects/air.jpeg"
    url: "https://github.com/Umesh1610/Airbnb_dbt"

  - title: "TPCH Snowflake DBT"
    category: "DBT"
    image: "config/assets/projects/tpch.png"
    url: "https://github.com/Umesh1610/dbt-project-tpch"


  - title: "AWS Certified Solutions Architect – Associate"
    category: "Certifications"
    image: "config/assets/projects/aws.png"
    url: "https://www.credly.com/badges/0b980a84-dc7d-46fb-b51d-3c4879cb350b/linked_in_profile"

  - title: "Azure Data Engineer Associate"
    category: "Certifications"
    image: "config/assets/projects/azure.png"
    url: "https://learn.microsoft.com/en-us/users/umeshreddymavurapu-8520/credentials/f64c9e903ec4b19b?ref=https%3A%2F%2Fwww.linkedin.com%2F"

  - title: "Databricks Certified Data Engineer Professional"
    category: "Certifications"
    image: "config/assets/projects/dbx.png"
    url: "https://credentials.databricks.com/818f6450-885f-42ff-9d02-632aac276c23#acc.t7Q8mRXj"

  - title: "Python for Data Science, AI & Development"
    category: "Certifications"
    image: "config/assets/projects/pai.jpg"
    url: "https://www.coursera.org/account/accomplishments/verify/83JEMRJA4LLN"

  - title: "Data Visualization with Python by IBM"
    category: "Certifications"
    image: "config/assets/projects/dpy.jpg"
    url: "https://www.coursera.org/account/accomplishments/certificate/QMR7SWK3JPKQ?utm_medium=certificate&utm_source=link&utm_campaign=copybutton_certificate"
       

  - title: "Crypto Dashboard Looker "
    category: "Data Visualization"
    image: "config/assets/projects/project-2.png"
    url: "https://github.com/Umesh1610/Crypto-real-time-Price-Tracking-GCP/tree/main/looker_screenshots"

  - title: "Netflix Dashboard"
    category: "Data Visualization"
    image: "config/assets/projects/Netflix.png"
    url: "https://public.tableau.com/app/profile/umesh.reddy.mavurapu/viz/Netflix_17316067362850/Netflix"

  - title: "Employee Attrition Analysis"
    category: "Data Visualization"
    image: "config/assets/projects/emp.png"
    url: "https://public.tableau.com/app/profile/umesh.reddy.mavurapu/viz/AttritionAnalysis_17316093212460/Dashboard2"

  - title: "Retail Customer Analysis"
    category: "Analytics"
    image: "config/assets/projects/retail.png"
    url: "https://github.com/Umesh1610/Retail-Customer-Analysis"

  - title: "H&M Web Analytics"
    category: "Analytics"
    image: "config/assets/projects/hm.png"
    url: "https://github.com/Umesh1610/H-M-Web-Analytics-Project"

  - title: "Leetcode 50 SQL"
    category: "SQL"
    image: "config/assets/projects/sql50.png"
    url: "https://github.com/Umesh1610/Leetcode-50-SQL"

  - title: "Python Calculator"
    category: "Applications"
    image: "config/assets/projects/pycal.jpeg"
    url: "https://github.com/Umesh1610/Python-Calculator"

  - title: "Tower of Hanoi - Interstellar Edition"
    category: "Applications"
    image: "config/assets/projects/tower.png"
    url: "https://67d73a40cf00c405b8782a50--splendid-queijadas-986bfc.netlify.app/"
