HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2022 — 2024"
      institution: "University of Texas at Dallas"
      description: "Masters in Information Technology Management"

    - period: "2015 — 2019"
      institution: "Dhirubhai Ambani Institute of Information and Commnunication Technology"
      description: "Bachelors in Information and Communication Technology"
      
EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2019 — 2022"
      position: "Data Engineer - Capillary Technologies"
      description: "Architected scalable ETL pipelines with PySpark and Apache Airflow, migrating legacy workflows to dbt models. Enabled real-time data processing using AWS Glue and delivered impactful insights through Power BI, focusing on optimizing query performance."
    - period: "2023 — 2025"
      position: "Data Engineer"
      description: "Led the design and optimization of Snowflake data marts and automated ETL pipelines using Azure Data Factory, improving marketing analytics workflows. Enhanced data quality using Azure Databricks and implemented CI/CD pipelines for seamless deployments."
      
LANGUAGES:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "Inglés"
      proficiency: "60%"
    - language: "Francés"
      proficiency: "40%"
      
SKILLS:
  enabled: true
  #display_progress_bars: true
  #display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Programming                      : MySQL, Python, Spark/Pyspark"
      proficiency: "80%"
    - skill: "Cloud                           : AWS, Azure, GCP"
      proficiency: "70%"
    - skill: "Data Warehousing                : Snowflake, Redshift, Bigquery"
      proficiency: "90%"
    - skill: "Data Processing & Orchestration : Glue, Azure Datafactory, Airflow, DBT"
      proficiency: "50%"
    - skill: "Monitoring & Data Quality       : Great Expectations, Datadog, CloudWatch "
      proficiency: "50%"
    - skill: "Infrastructure & DevOps         : Docker, Terraform, Kubernetes, GitHub Actions "
      proficiency: "50%"
    - skill: "Data Streaming                  : Kafka, Kinesis, Pub/Sub, Spark Streaming"
      proficiency: "50%"
    - skill: "Visualization tools             : Tableau, Power BI, Looker"
      proficiency: "50%"
    - skill: "Version Control & Collaboration : Git, GitHub "
      proficiency: "50%"

