HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
     - period: "2022 — 2024"
      institution: "University of Texas at Dallas"
      degree: "Masters in Information Technology Management"

     - period: "2015 — 2019"
      institution: "Dhirubhai Ambani Institute of Information and Commnunication Technology"
      description: "Bachelors in Information and Communication Technology"

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2019 — 2022"
      position: "Data Engineer"
      description: ""
    - period: "2023 — 2025"
      position: "Data Engineer"
      description: ""
   


SKILLS:
  enabled: true
  #display_progress_bars: true
  #display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Python"
      proficiency: "80%"
    - skill: "SQL"
      proficiency: "70%"
    - skill: "Spark"
      proficiency: "90%"
    - skill: "ETL/ELT"
      proficiency: "50%"
