HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2022 — 2024"
      institution: "University of Texas at Dallas"
      description: "Masters in Information Technology Management"

    - period: "2015 — 2019"
      institution: "Dhirubhai Ambani Institute of Information and Commnunication Technology"
      description: "Bachelors in Information and Communication Technology"
      
EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2010 — 2013"
      position: "Web Designer"
      description: "Worked on the design and development of websites for small to medium-sized businesses. Collaborated closely with developers to ensure responsive and user-friendly designs. Led the redesign of the company’s website, improving user engagement by 25%."
    - period: "2013 — 2015"
      position: "Art Director"
      description: "Led a team of designers to create visually stunning campaigns for major clients in the advertising industry. Managed the creative direction of print and digital media, ensuring consistent branding and high-quality designs. Oversaw the production of advertisements that won industry awards."
    - period: "2015 — Present"
      position: "Creative Director"
      description: "Direct and oversee the creative process for a range of projects, from concept to execution. Lead cross-functional teams to create innovative design solutions for branding, marketing, and digital experiences. Recently led the redesign of a global brand’s digital presence, increasing online sales by 40%."

LANGUAGES:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "Inglés"
      proficiency: "60%"
    - language: "Francés"
      proficiency: "40%"
      
SKILLS:
  enabled: true
  #display_progress_bars: true
  #display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "MySQL"
      proficiency: "80%"
    - skill: "Python"
      proficiency: "70%"
    - skill: "Spark/Pyspark"
      proficiency: "90%"
    - skill: "ETL/ELT"
      proficiency: "50%"
    - skill: "Data Analysis"
      proficiency: "50%"
    - skill: "Data Visualization"
      proficiency: "50%"
