HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2022 — 2024"
      institution: "University of Texas at Dallas"
      description: "Masters in Information Technology Management"

    - period: "2015 — 2019"
      institution: "Dhirubhai Ambani Institute of Information and Commnunication Technology"
      description: "Bachelors in Information and Communication Technology"
      
EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2019 — 2022"
      position: "Data Engineer"
      description: "Capillary Technologies"
    - period: "2023 — 2025"
      position: "Data Engineer"
      description: "Metlife"
      
LANGUAGES:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "Inglés"
      proficiency: "60%"
    - language: "Francés"
      proficiency: "40%"
      
SKILLS:
  enabled: true
  #display_progress_bars: true
  #display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "MySQL"
      proficiency: "80%"
    - skill: "Python"
      proficiency: "70%"
    - skill: "Spark/Pyspark"
      proficiency: "90%"
    - skill: "ETL/ELT"
      proficiency: "50%"
    - skill: "Data Analysis"
      proficiency: "50%"
    - skill: "Data Visualization"
      proficiency: "50%"
